### ISSUE TITLE
Добавьте пожалуйста ссылку на ютуб-канал математика, упомянутого в Episode 131 

### ISSUE THREAD

**Issue by ffbit** [razbor-poletov/razbor-poletov.github.com#106]
Интересно же!

//cc @23derevo @antonarhipov

**Comment by antonarhipov** [comment]
Конкретного канала Савватеева на ютюбе не знаю. Но многие его лекции находятся там на ура https://www.youtube.com/results?search_query=%D1%81%D0%B0%D0%B2%D0%B2%D0%B0%D1%82%D0%B5%D0%B5%D0%B2

**Comment by ffbit** [comment]
@antonarhipov, спасибо за фамилию математика (я не смог её разобрать в выпуске подкаста) и ссылку на ютуб.
