### ISSUE TITLE
Modern Web Application Development for Java Programmers

### ISSUE THREAD

**Issue by DmitriySh** [razbor-poletov/razbor-poletov.github.com#35]
Привет, Виталий!

Будет ли "Modern Web Application Development for Java Programmers" в 2015 с твоим участием?

**Comment by gAmUssA** [comment]
@DmitriySh Я Виктор :) Если пригласят, то буду, но пока не поступало предложения

**Comment by jbaruch** [comment]
Вииитаааалик!
