### ISSUE TITLE
Gitter Chat

### ISSUE THREAD

**Issue by IRus** [razbor-poletov/razbor-poletov.github.com#39]
Привет!

Я думаю вашему подкасту не хватает чата на гиттере, вот пример чата: https://gitter.im/JavaBy/chat

Для создания чата и участия в нем нужен всего лишь GitHub аккаунт.

**Comment by jbaruch** [comment]
:+1:
Вместо этого допотопного ирка.

**Comment by w32blaster** [comment]
ирк не допотопный. Это - классика!

**Comment by jbaruch** [comment]
Как "жигули классика".

**Comment by jbaruch** [comment]
Дисклеймер - это я в свое время предложил ирк.

**Comment by IRus** [comment]
Java тоже допотопная частично :trollface:

**Comment by jbaruch** [comment]
Есть такое дело.

**Comment by IRus** [comment]
@abashev , @gAmUssA  что вы думаете по этому поводу? (cc @antonarhipov @jbaruch @dmitryc )

**Comment by antonarhipov** [comment]
Дык чат уже завели же. На Gitter, всё ОК. Радуемся.

**Comment by IRus** [comment]
@antonarhipov каюсь, не заметил
